-- Lab 4: Actions Taken, the Ticket version, and the time a Ticket was resolved.
--
-- Generated by `prisma migrate dev --create-only`, then extended by hand with
-- the two things Prisma cannot write: the backfill in step 2 and the CHECK in
-- step 3. Everything here adds. No existing column, row or constraint is
-- changed or removed (specification.md 7.2, BR-32), and the way back is
-- prisma/rollback/lab4_down.sql.

-- 1. Every existing Ticket starts at version 1. The default does this without
--    rewriting a row.
ALTER TABLE "Ticket" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;

-- 2. A Ticket that is already Resolved or Closed takes its resolution time
--    from the last time it was written, which is the closest thing Lab 3
--    recorded. Every other Ticket stays NULL. Both columns are TIMESTAMP(3),
--    so no time zone is involved in the copy, and "updatedAt" itself is not
--    touched: Prisma maintains it from the client, not with a trigger.
ALTER TABLE "Ticket" ADD COLUMN "resolvedAt" TIMESTAMP(3);
UPDATE "Ticket" SET "resolvedAt" = "updatedAt" WHERE "currentStatus" IN ('RESOLVED', 'CLOSED');

-- 3. Actions Taken. No rows are written for existing Tickets: a legacy Ticket
--    has no recorded work, and inventing some would be a lie in a table whose
--    whole purpose is to say what was done.
CREATE TABLE "ActionTaken" (
    "id" SERIAL NOT NULL,
    "ticketId" INTEGER NOT NULL,
    "performedById" INTEGER NOT NULL,
    "actionAt" TIMESTAMP(3) NOT NULL,
    "description" TEXT NOT NULL,
    "result" TEXT NOT NULL,
    "followUpRequired" BOOLEAN NOT NULL DEFAULT false,
    "followUpNote" TEXT,
    "attachmentNotes" TEXT,
    "version" INTEGER NOT NULL DEFAULT 1,
    "requestKey" TEXT NOT NULL,
    "editedById" INTEGER,
    "editedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ActionTaken_pkey" PRIMARY KEY ("id"),
    -- BR-07: a follow-up note exists exactly when follow-up is required. The
    -- API validates the same thing; this holds for every other writer too.
    CONSTRAINT "ActionTaken_followUp_check" CHECK ("followUpRequired" = ("followUpNote" IS NOT NULL))
);

CREATE UNIQUE INDEX "ActionTaken_requestKey_key" ON "ActionTaken"("requestKey");
CREATE INDEX "ActionTaken_ticketId_actionAt_idx" ON "ActionTaken"("ticketId", "actionAt");
CREATE INDEX "ActionTaken_performedById_actionAt_idx" ON "ActionTaken"("performedById", "actionAt");

ALTER TABLE "ActionTaken" ADD CONSTRAINT "ActionTaken_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "Ticket"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ActionTaken" ADD CONSTRAINT "ActionTaken_performedById_fkey" FOREIGN KEY ("performedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ActionTaken" ADD CONSTRAINT "ActionTaken_editedById_fkey" FOREIGN KEY ("editedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- 4. The dashboards' "recently updated" lists.
CREATE INDEX "Ticket_updatedAt_idx" ON "Ticket"("updatedAt");
